project:
  type: website

website:
  title: "Manual for Data Analysts"
  navbar:
    background: primary
    left:
      - href: workflow.qmd
        text: Workflow

format:
  html:
    theme: cosmo
    toc: true